version: "3.8"

services:
  
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  cache:
    image: redis:latest
    restart: always

  backend_django:
    build: ./Backend_Django
    ports:
      - "8000"
    restart: always
    environment:
      - REDIS_HOST=cache
      - PGHOST=db
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - CORS_ALLOWED_ORIGINS=http://frontend_vuejs:80,http://backend_django:8000
    depends_on:
      - db
      - cache

  frontend_vuejs:
    build: ./Frontend_vuejs
    ports:
      - "80:80"
    restart: always
    environment:
      - VUE_APP_ROOT_API=http://backend_django:8000/api/
      - backend_host=http://backend_django:8000

    depends_on:
      - backend_django
    command: >
      /bin/sh -c
      "envsubst '
      $${backend_host}
      '< /etc/nginx/nginx.conf.template
      > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'"